title: "Portfolio Wissam"
description: "Portfolio et projets de Wissam"
baseurl: "/wd"        
url: "https://wissamdr6.github.io"
theme: jekyll-theme-primer
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
